# model load 
training:
  base_model: "paust/pko-flan-t5-large"
  output_dir: "restore-t5"  
  t5_dir: "t5_ft" 
  eval_strategy: "steps"  
  eval_steps: 100  
  batch_size: 1 
  gradient_accumulation_steps: 8 
  epochs: 3.0
  lr_scheduler_type: "linear"  
  learning_rate: 2e-04
  warmup_ratio: 0.06
  logging_strategy : "steps"
  logging_steps: 10
  eval_strategy : "steps"
  save_strategy: "epoch"
  seed: 42  
  optimizer : "adamw_torch"


# data load
data:
  path: "../data/aug_inference.csv"  # 데이터셋 경로